options {
    directory "/var/cache/bind";
    allow-query { any; };
    forwarders {
        8.8.8.8;
        8.8.4.4;
    };
    recursion yes;
};

zone "arena.com" {
    type master;
    file "/etc/bind/arena.com.zone";
};